title       = "tapas"
baseURL     = "https://tapas-cli.tamnd.com/"
description = "Read Tapas.io comics and novel series"
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/tapas-cli"
